In [62]:
# Initialize Otter
import otter
grader = otter.Notebook("lab.ipynb")

# Lab 1 – Python, NumPy, and Pandas

## DSC 80, Fall 2026

### Due Date: Wednesday, October 7, 2026 at 11:59 p.m. Pacific

## Instructions

Welcome to the first assignment in DSC 80 this quarter!

Much like in DSC 10, this Jupyter Notebook contains the statements of the problems and provides code and Markdown cells to display your answers to the problems. Unlike DSC 10, the notebook is *only* for displaying a readable version of your final answers. The coding will be done in an accompanying `lab.py` file that is imported into the current notebook, and **you will only submit that `lab.py` file**, not this notebook!

Some additional guidelines:
- **Unlike in DSC 10, labs will have both public tests and hidden tests.** The bulk of your grade will come from your scores on hidden tests, which you will only see on Gradescope after the assignment deadline.
- **Do not change the function names in the `lab.py` file!** The functions in the `lab.py` file are how your assignment is graded, and they are graded by their name. If you changed something you weren't supposed to, you can find the original code in the [course GitHub repository](https://github.com/dsc-courses/dsc80-2026-fa).
- Notebooks are nice for testing and experimenting with different implementations before designing your function in your `lab.py` file. You can write code here, but make sure that all of your real work is in the `lab.py` file, since that's all you're submitting.
- You are encouraged to write your own additional helper functions to solve the lab, as long as they also end up in `lab.py`.

**To ensure that all of the work you want to submit is in `lab.py`, we've included a script named `lab-validation.py` in the lab folder. You shouldn't edit it, but instead, you should call it from the command line (e.g. the Terminal) to test your work.** More details on its usage are given at the bottom of this notebook.

**Importing code from `lab.py`**:

* Below, we import the `.py` file that's contained in the same directory as this notebook.
* We use the `autoreload` notebook extension to make changes to our `lab.py` file immediately available in our notebook. Without this extension, we would need to restart the notebook kernel to see any changes to `lab.py` in the notebook.
    - `autoreload` is necessary because, upon import, `lab.py` is compiled to bytecode (in the directory `__pycache__`). Subsequent imports of `lab` merely import the existing compiled python.

In [63]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [64]:
from lab import *

In [65]:
from pathlib import Path
import io
import pandas as pd
import numpy as np

### Infrastructure Summary

Run the following cell to see a [video 🎥](https://www.loom.com/share/0ea254b85b2745e59322b5e5a8692e91?sid=b77c5c2d-0c24-40fb-8cfc-8574d49d9019) that summarizes the above information and walks you through how to
- set up your programming environment (see the instructions in [Tech Support](https://dsc80.com/tech_support) for more details),
- access assignments,
- work on and test assignments, and
- submit assignments.

The video is also linked on the [Resources tab of the course website](https://dsc80.com/resources).

In [66]:
from IPython.display import IFrame
IFrame(src="https://www.loom.com/embed/0ea254b85b2745e59322b5e5a8692e91", width=750, height=500)

Let's get started! 🎉

## Part 1: Python Basics 🐍

### Question 0 – Consecutive Integers

Complete the implementation of the function `consecutive_ints`, which takes in a possibly empty list of integers (`ints`) and returns `True` if there exist two adjacent list elements that are consecutive integers and `False` otherwise.

For example, since `9` is next to `8`, `consecutive_ints([5, 3, 6, 4, 9, 8])` should evaluate to `True`, since `9` and `8` are consecutive integers. On the other hand, `consecutive_ints([1, 3, 5, 7, 9])` should evaluate to `False`.

***Note***: If you look at `lab.py`, you'll notice that the solution to this problem is already there. This question is done for you to show you what a completed homework problem looks like.

In [67]:
# The cells below are here for you to write scratch work in. 
# You should write the code for your answer in `lab.py`, not here.

To run the public tests on your code for a given question, run the cell containing a call to `grader.check` that immediately follows it. 

Remember, your grade will primarily be determined by hidden tests, which are **not** run when you run `grader.check`, so it's important to extensively test your functions on your own by calling them on different inputs. Does they work for edge cases? Real-world data is **very messy** and you should expect your data processing code to break without thorough testing!

You can write custom tests either by calling your functions on different inputs here in the notebook, or by writing doctests in `lab.py`, as you did in DSC 20.

In [68]:
grader.check("q0")

q0 results: All test cases passed!

### Question 1 – Median vs. Mean

Complete the implementation of the function `median_vs_mean`, which takes in a non-empty list of numbers (`nums`) and returns `True` if median of the list is less than or equal to the mean of the list and `False` otherwise.

Recall, if a list has even length, the median is the mean of the middle two elements.

***Note:*** In this question, you may only use built-in functions and methods in Python. You should not use `numpy` or `pandas` at all, nor should you import any additional packages.

In [69]:
def median_vs_mean(nums):
    sorted_nums = sorted(nums) # O(nlogn)
    middle = len(sorted_nums) // 2

    if len(sorted_nums) == 0:
        return True # per DSC 40B, anything related to an empty array is by convention, vaccuously true

    if len(sorted_nums) % 2 == 0:
        return (sorted_nums[middle-1] + sorted_nums[middle])/2 <= sum(sorted_nums)/len(sorted_nums)
    return sorted_nums[middle] <= sum(sorted_nums)/len(sorted_nums)

In [70]:
meow = [50, 20, 15, 40]
sorted_meow = sorted(meow)

mean = sum(meow)/len(meow)

print(meow)
print(sorted_meow)
print(mean)

[50, 20, 15, 40]
[15, 20, 40, 50]
31.25

In [71]:
mid = len(sorted_meow) // 2
(sorted_meow[mid-1] + sorted_meow[mid])/2 <= sum(sorted_meow)/len(sorted_meow)

True

In [72]:
median_vs_mean([50, 20, 15, 40])

True

In [73]:
grader.check("q1")

q1 results: All test cases passed!

## Part 2: Strings and Files 🧵

The following questions will familiarize you with the basics of working with strings and reading data from files. Remember that by default, data from files are stored as strings in Python.

### Question 2 – $n$ Prefixes

Complete the implementation of the function `n_prefixes`, which takes a string `s` and a positive integer `n`. It returns a string containing the first `n` consecutive prefixes of `s` in reverse order.

For example, let's suppose `s` is the string `'Billy!'` and `n` is `4`. The consecutive prefixes of `'Billy!'` are:
- `'B'`
- `'Bi'`
- `'Bil'`
- `'Bill'`
- `'Billy'`
- `'Billy!'`

The first 4 of these are `'B'`, `'Bi'`, `'Bil'`, and `'Bill'`. If we combine these 4 in reverse order, we get `'BillBilBiB'`, which is what `n_prefixes('Billy!', 4)` should return. As another example, `n_prefixes('Marina', 3)` should return `'MarMaM'`. **You may assume that `n` is no larger than the length of `s`.**

***Hint:*** Recall that [strings may be sliced](https://docs.python.org/3/tutorial/introduction.html#strings), like lists.

In [74]:
billy = "billy"
billy[:700]

'billy'

In [75]:
"".join([billy[:i] for i in range(3+1)])

'bbibil'

In [76]:
def n_prefixes(s, n):
    return "".join([s[:i] for i in range(n+1)][::-1])

In [77]:
n_prefixes('Billy', 4)

'BillBilBiB'

In [78]:
grader.check("q2")

q2 results: All test cases passed!

### Question 3 – Exploded Numbers 💣

Complete the implementation of the function `exploded_numbers`, which takes in a list of integers (`ints`) and a non-negative integer (`n`) and **returns a list of strings** containing numbers from the list expanded by `n` numbers in both directions, separated by spaces. Each integer should be [zero padded](https://www.tutorialspoint.com/python/string_zfill.htm) so that all integers outputted have the same length.

For example, consider `exploded_numbers([3, 8, 15], 2)`.
- If we explode 3 by 2 numbers in both directions, we get 1, 2, 3, 4, 5.
- If we explode 8 by 2 numbers in both directions, we get 6, 7, 8, 9, 10.
- If we explode 15 by 2 numbers in both directions, we get 13, 14, 15, 16, 17.

The longest length of any of the exploded numbers above is 2, so all of the outputted integers should have length 2.

- The string corresponding to 3 in the input is `'01 02 03 04 05'`.
- The string corresponding to 8 in the input is `'06 07 08 09 10'`.
- The string corresponding to 15 in the input is `'13 14 15 16 17'`.

So, `exploded_numbers([3, 8, 15], 2)` should return `['01 02 03 04 05', '06 07 08 09 10', '13 14 15 16 17']`. 

As another example, `exploded_numbers([9, 99], 3)` should return `['006 007 008 009 010 011 012', '096 097 098 099 100 101 102']`.

***Note***: You can assume that negative numbers will never be encountered. That is, when testing your code, we will never explode a number so much that it becomes negative.

In [79]:
def exploded_numbers(ints, n):
    pads = len(str(max(ints)+n))

    return [" ".join(
        [str(num-dx).zfill(pads) for dx in range(n,0,-1)] +
        [str(num+dx).zfill(pads) for dx in range(n+1)]
        ) for num in ints]

In [80]:
exploded_numbers([3, 8, 15], 2)

['01 02 03 04 05', '06 07 08 09 10', '13 14 15 16 17']

In [81]:
exploded_numbers([9, 99], 3)

['006 007 008 009 010 011 012', '096 097 098 099 100 101 102']

In [82]:
grader.check("q3")

q3 results: All test cases passed!

### Question 4 – Reading Files

[Recall](https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files) that the built-in function `open` takes in a file path and returns *a file object* (sometimes called a *file handle*). Below are a few properties of file objects:

* `open(path)` opens the file at location `path` for reading.
* `open(path)` is an *iterable*, which contains successive lines of the file.
* Once a file object is opened, after use it should be closed to avoid memory leaks. To ensure a file is closed once done, you should use a *context manager* as follows:
```py
with open(path) as fh:
    for line in fh:
        process_line(line)
```
* To read the entire file into a string, use the `read` method:
```py
with open(path) as fh:
    s = fh.read()
```

However, you should be careful when reading an entire file into memory that the file isn't too big! *You should avoid this whenever possible!*

Complete the implementation of the function `last_chars`, which takes in file object (`fh`) and returns a string consisting of the last character of each line. Note that you don't have to use `open` at all; the argument given to you is a file object, not a file path.

***Note:*** A newline (`'\n'`) is the "delimiter" of the lines of a file, and doesn't count as part of the line (as the tests imply). Every other character is part of the line. For more info on this, see [the interpretation](https://en.wikipedia.org/wiki/Newline#Interpretation) of files as a 'newline delimited variables' file.

In [83]:
def last_chars(fh):
    last_chars_str = ""
    for line in fh:
        last_chars_str += line.rstrip('\n')[-1]

    return last_chars_str

If your implementation is correct, you should see `'hrg'` when running the cell below:

In [84]:
# You'll see the Path(...) / syntax a lot.
# It creates the correct path to your file, 
# whether you're using Windows, macOS, or Linux.
# (Note that macOS and Linux use / to denote separate folders in paths,
# while Windows uses \.)

fp = Path('data') / 'chars.txt'
last_chars(open(fp))

'hrg'

In [85]:
grader.check("q4")

q4 results: All test cases passed!

## Part 3: `numpy` exercises 🥧

For a refresher on `numpy` and arrays, refer to the relevant section of the [DSC 10 course notes](https://notes.dsc10.com/02-data_sets/arrays.html).

### Question 5 – Array Methods

Complete the implementations of the functions `add_root` and `where_square`. Specifications are given below. Your solutions should **not** contain any loops or list comprehensions.

#### `add_root`

`add_root` should take in a `numpy` array, `A`, and return a new `numpy` array that contains the element-wise sum of the elements in `A` with the _square roots of the positions of the elements in `A`_. 

For instance, if `A` contains the values 5, 9, and 4, the output array should contain the values 5 (5 + $\sqrt{0}$), 10 (9 + $\sqrt{1}$), and 5.4142... (4 + $\sqrt{2}$).

<br>

#### `where_square`

`where_square` should take in a `numpy` array, `A`, and return a new `numpy` array of Booleans whose `i`th element is `True` if and only if the `i`th element of `A` is a perfect square. 

For instance, `where_square(np.array([2, 9, 16, 15]))` should return `array([False, True, True, False])`.

In [86]:
4.0 == 4

True

In [87]:
def add_root(A):
    B = A.copy()
    C = np.arange(B.shape[0])
    return B + np.sqrt(C)


def where_square(A):
    return np.array(np.sqrt(A) == np.floor(np.sqrt(A)))

In [88]:
# Don't change this cell -- it is needed for the tests to work
A_1 = np.array([2, 4, 6, 7])
out_1 = add_root(A_1)

A_2 = np.array([1, 2, 16, 17, 32, 49])
out_2 = where_square(A_2)

In [89]:
out_2

array([ True, False,  True, False, False,  True])

In [90]:
grader.check("q5")

q5 results: All test cases passed!

### Question 6 - Filtering Matrices

Complete the implementation for the function `filter_cutoff_loop` and `filter_cutoff_np`.

#### Part 1: `filter_cutoff_loop`

`filter_cutoff_loop` should take in a matrix (2-dimensional `numpy` array) and a `float` cutoff. The function should return a 2-dimensional `numpy` array with only coumns that have a column mean (strictly) greater than the cutoff value. **This function should be implemented with loops or list comprehensions, not using `numpy` or `pandas` operations.** For example, given the matrix: 

$$
a = \begin{bmatrix}
    1 & -2 & 3 & -3 \\
    0 & 1 & 3 & 6 \\
\end{bmatrix}
$$
The column means are computed as follows: 
$$
\begin{bmatrix}
1\\
0
\end{bmatrix} 
= \frac{1+0}{2} = 0.5 \text{, }
\begin{bmatrix}
-2\\
1
\end{bmatrix} 
= \frac{-2+1}{2} = 0.5 \text{, }
\begin{bmatrix}
3\\
3
\end{bmatrix} 
= \frac{3+3}{2} = 3 \text{, }
\begin{bmatrix}
-3\\
6
\end{bmatrix} 
= \frac{-3+6}{2} = 1.5
$$

If the cutoff value is 1, only the last two columns have means above 1, thus only the last two columns are kept, as shown in the first example below. 

```py
>>> a = np.array([[1,-2, 3,-3], [0, 1, 3, 6]])
>>> filter_cutoff_loop(a, 1.0)
# the column means are [0.1,-0.5, 3, 1.5]
# only columns 3 & 4 have column means higher than 1
# we only return columns 3 & 4
array([[ 3, -3],
       [ 3,  6]])
```

```py
>>> a = np.array([[1,-2, 3,-3], [0, 1, 3, 6]])
>>> filter_cutoff_loop(a, 2.0)
# the column means are [0.1,-0.5, 3, 1.5]
# only column 3 has a column mean higher than 2
# we only return column 3
array([[3],
       [3]])
```

In [91]:
def filter_cutoff_loop(matrix, cutoff):
    masks = [sum([matrix[i][j] for i in range(matrix.shape[0])])/matrix.shape[0] > cutoff for j  in range(matrix.shape[1])]
    return matrix[:, masks]

In [92]:
a = np.array([[1, -2, 3, -3], [0, 1, 3, 6]])
a

array([[ 1, -2,  3, -3],
       [ 0,  1,  3,  6]])

In [93]:
test_cutoff = 0
masks = [sum([a[i][j] for i in range(a.shape[0])])/a.shape[0] > 0 for j  in range(a.shape[1])]
a[:, masks]

array([[ 1,  3, -3],
       [ 0,  3,  6]])

In [94]:
filter_cutoff_loop(a, 0)

array([[ 1,  3, -3],
       [ 0,  3,  6]])

In [95]:
grader.check("q6")

q6 results: All test cases passed!

### Question 6

#### Part 2: `filter_cutoff_np`

`filter_cutoff_np` should take in the same inputs and output the same results as  `filter_cutoff_loop`.  **Do not use loops or list comprehensions for this implementation, only `numpy` operations.**


***Hints:***: 
- What does the axis argument do in `np.mean`?
- Remember we can slice arrays using Boolean values. How does the code below work? 
```py
>>> a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
>>> a[:, [True, False, True, False]]
```

In [96]:
def filter_cutoff_np(matrix, cutoff):
    masks = np.mean(matrix, axis=0) > cutoff
    return matrix[:, masks]

In [97]:
b = np.array(
    [[1, 9, -4], 
     [0, 3, 6], 
     [0, 8, 2],
     [5, 6, 7]])
b

array([[ 1,  9, -4],
       [ 0,  3,  6],
       [ 0,  8,  2],
       [ 5,  6,  7]])

In [98]:
test_cutoff = 3
mask2 = np.mean(b, axis=0) > test_cutoff
mask2

array([False,  True, False])

In [99]:
b[:, mask2]

array([[9],
       [3],
       [8],
       [6]])

In [100]:
a = np.array([[1,-2, 3,-3], [0, 1, 3, 6]])
a

array([[ 1, -2,  3, -3],
       [ 0,  1,  3,  6]])

In [101]:
filter_cutoff_np(a, 1)

array([[ 3, -3],
       [ 3,  6]])

In [102]:
grader.check("q6.2")

q6.2 results: All test cases passed!

### Question 7 – Stock Prices 📈

Complete the implementations of the functions `growth_rates` and `with_leftover`. Specifications are given below. Your solutions should **not** contain any loops or list comprehensions.

#### `growth_rates`

`growth_rates` should take in a `numpy` array, `A`, of [stock prices](https://en.wikipedia.org/wiki/Stock) for a single stock on successive days in USD. It should return an array of growth rates. That is, the `i`th number of the returned array should contain the rate of growth in stock price between the $i^{th}$ day to the $(i+1)^{th}$ day. The growth rate between two values is defined as $\frac{\text{final} - \text{initial}}{\text{initial}}$. You should return growth rates as **proportions, rounded to two decimal places**.

<br>

#### `with_leftover`

Again, suppose `A` is a `numpy` array of stock prices. Consider the following scheme: 

- Suppose that you start each day with \$20 to purchase stocks. 
- Each day, you purchase as many shares as possible of the stock. (The price changes each day, according to `A`.)
- Any money left-over after a given day is saved for possibly buying stock on a future day.

The function `with_leftover` should take in `A` and return the day (as an `int`) on which you can buy at least one full share using just "left-over" money. If this never happens, return `-1`. Note that the first stock purchase occurs on Day 0, and that you cannot purchase fractions of a share of a stock.

For example, if the stock price is \$3 every day, then the answer is `1` (corresponding to Day 1):
- Day 0: Buy 6 stocks with \$20, and \$2 is added to the leftover. Your total leftover is currently \$2. This is not enough to buy one extra share, so you continue.
- Day 1: Buy 6 stocks with \$20, and another \$2 is added to the leftover. Your total leftover is now \$4, so you can now buy one extra share. Hence, the answer is Day 1, and `with_leftover` should return `1`.

***Hint:*** `np.cumsum` may be helpful.

In [103]:
def growth_rates(A):
    final = np.array(A[1:])
    initial = np.array(A[:-1])

    rate = (final - initial)/initial
    return np.round(rate, 2)

def with_leftover(A):
    daily_leftover = 20%np.array(A)
    leftovers = np.cumsum(daily_leftover)
    days = np.argmax(leftovers >= A) 
    return days if days != 0 else -1

In [104]:
# Don't change this cell -- it is needed for the tests to work
fp = Path('data') / 'stocks.csv'
stocks = np.array([float(x) for x in open(fp)])
out_3_stocks = growth_rates(stocks)

A_4 = np.array([3, 3, 3, 3])
out_4 = with_leftover(A_4)

In [105]:
out_4

1

In [106]:
A = np.array([10., 12., 9., 9., 18., 24.])
expected = np.array([0.2, -0.25, 0., 1., 0.33])

A_padded = np.append(np.append(np.array([0]), A), np.array([0]))
print(A_padded)

B = A_padded.copy()
diffs = B[1:] - A_padded[:-1]
rate = (diffs/A_padded[:-1])[1:-1]
print(f"Calculated: {rate}\n Expected: {expected}")

[ 0. 10. 12.  9.  9. 18. 24.  0.]
Calculated: [ 0.2        -0.25        0.          1.          0.33333333]
 Expected: [ 0.2  -0.25  0.    1.    0.33]

C:\Users\IdeRy\AppData\Local\Temp\ipykernel_13384\758484964.py:9: RuntimeWarning: divide by zero encountered in divide
  rate = (diffs/A_padded[:-1])[1:-1]

In [107]:
growth_rates([1,2,3])

array([1. , 0.5])

In [108]:
yoo = np.array([9, 9, 9, 9, 9, 9]) 
aaa = [20%num for num in yoo]
bbb = np.cumsum(aaa)
np.argmax(bbb > yoo)

4

In [109]:
with_leftover(np.array([3, 3, 3, 3]))

1

In [110]:
9/2

4.5

In [111]:
grader.check("q7")

q7 results: All test cases passed!

## Part 4: Introduction to `pandas` 🐼

This part will help build familiarity with DataFrames in `pandas`. Fortunately, you've already a version of `pandas` before in DSC 10, called `babypandas`! Review the [DSC 10 course notes](https://notes.dsc10.com/02-data_sets/dataframes.html) as necessary.

One key difference between `babypandas` and `pandas` is the idiomatic way of accessing a column. In `babypandas`, to access column `'x'` in DataFrame `df`, you used `df.get('x')`. In `pandas`, the more common way is `df['x']`.

As always for `pandas` questions:
1. Avoid writing loops through the rows of the DataFrame to do the problem, and
2. Test the output/correctness of your code with the help of the dataset given, but be sure your code will also run on data that is similar to but different from the dataset given. (One way to do this is to sample rows from the provided DataFrame using the `.sample` method).

The file `data/salary.csv` contains salary information for the 2021-22 National Basketball Association (NBA) season 🏀. Specifically, it contains the name, team, and salary of all players who have played at least 15 games last season. We will load this file and store it as a DataFrame named `salary`.

In [112]:
# Do not edit this cell -- it is needed for the tests
salary_fp = Path('data') / 'salary.csv'
salary = pd.read_csv(salary_fp)
salary.head()

              Player Position           Team    Salary
0       John Collins       PF  Atlanta Hawks  23000000
1   Danilo Gallinari       PF  Atlanta Hawks  20475000
2  Bogdan Bogdanović       SG  Atlanta Hawks  18000000
3       Clint Capela        C  Atlanta Hawks  17103448
4       Delon Wright       SG  Atlanta Hawks   8526316

### Question 8 – `pandas` Basics

Your job is to complete the implementation of the function `salary_stats`, which takes in a DataFrame like `salary` and returns a **Series** containing the following statistics:
- `'num_players'`: The number of players.
- `'num_teams'`: The number of teams.
- `'total_salary'`: The total salary amount for all players.
- `'highest_salary'`: The name of the player with the highest salary. **Assume there are no ties.**
- `'avg_los'`: The average salary of the `'Los Angeles Lakers'`, rounded to two decimal places.
- `'fifth_lowest'`: The name and team of the player who has the fifth lowest salary, separated by a comma and a space (e.g. `'Billy Triton, Cleveland Cavaliers'`). **Assume there are no ties.**
- `'duplicates'`: A Boolean that is `True` if there are any duplicate last names, and `False` otherwise. Note that some players may have a suffix on their name, such as "Jr." or "III" -- you should ignore these. That is, "Billy Triton Jr." and "Tyler Triton" should be considered to have the same last name.
- `'total_highest'`: The total salary of the team that has the highest paid player.

The index of each element in the outputted Series is specified above.

***Notes***: 
- Your function should work on a dataset of the same format that contains information from other years. This means that `salary_stats` should not "hard-code" any numbers or strings, but should compute them all programatically. In all cases, you may assume that none of the answers involving ranking involves a tie.
- The public tests don't test to see if your function actually returns the right numbers. You should manually inspect your result to make sure that all values seem appropriate.

In [113]:
def salary_stats(salary):
    highest_salary_guy = salary.sort_values(by='Salary', ascending=False)['Player'].iloc[0]
    highest_salary_guys_team = salary[salary['Player'] == highest_salary_guy]['Team'].iloc[0]
    sorted_by_salary = salary.sort_values(by='Salary', ascending=True)

    statistics = {
        'num_players': salary.shape[0],
        'num_teams': salary.groupby('Team').count().shape[0],
        'total_salary': salary['Salary'].sum(),
        'highest_salary': highest_salary_guy,
        'avg_los': round(salary[['Team', 'Salary']].groupby('Team').mean().loc['Los Angeles Lakers'].iloc[0], 2),
        'fifth_lowest': f'{sorted_by_salary["Player"].iloc[4]}, {sorted_by_salary["Team"].iloc[4]}',
        'duplicates': len(np.unique(np.array(list(map(lambda name : name.split()[1], salary['Player'].to_list()))))) != salary.shape[0],
        'total_highest': salary[salary['Team'] == highest_salary_guys_team]['Salary'].sum()
    }
    return pd.Series(statistics)

In [114]:
highest_salary_guy = salary.sort_values(by='Salary', ascending=False)['Player'].iloc[0]
highest_salary_guys_team = salary[salary['Player'] == highest_salary_guy]['Team'].iloc[0]
sorted_by_salary = salary.sort_values(by='Salary', ascending=True)
print(salary.shape[0])
print(salary.groupby('Team').count().shape[0])
print(salary['Salary'].sum())
print(salary.sort_values(by='Salary', ascending=False)['Player'].iloc[0])
print(salary[['Team', 'Salary']].groupby('Team').mean().loc['Los Angeles Lakers'].iloc[0])
print(f'{sorted_by_salary["Player"].iloc[4]}, {sorted_by_salary["Team"].iloc[4]}')
print(len(np.unique(np.array(list(map(lambda name : name.split()[1], salary['Player'].to_list()))))) != salary.shape[0])
print(salary[salary['Team'] == highest_salary_guys_team]['Salary'].sum())

381
30
3433118794
Stephen Curry
13266896.818181818
Miye Oni, Oklahoma City Thunder
True
130428103

In [115]:
len(np.unique(np.array(list(map(lambda name : name.split()[1], salary['Player'].to_list()))))) != salary.shape[0]

True

In [116]:
highest_salary_guy = salary.sort_values(by='Salary', ascending=False)['Player'].iloc[0]
highest_salary_guys_team = salary[salary['Player'] == highest_salary_guy]['Team'].iloc[0]
salary[salary['Team'] == highest_salary_guys_team]['Salary'].sum()

130428103

In [117]:
# Do not edit this cell -- it is needed for the tests
salary_fp = Path('data') / 'salary.csv'
salary = pd.read_csv(salary_fp)
stats = salary_stats(salary)

salary_sample_fp = Path('data') / 'salary_sample.csv'
salary_sample = pd.read_csv(salary_sample_fp)
sample_stats = salary_stats(salary_sample)

In [118]:
stats

num_players                                   381
num_teams                                      30
total_salary                           3433118794
highest_salary                      Stephen Curry
avg_los                               13266896.82
fifth_lowest      Miye Oni, Oklahoma City Thunder
duplicates                                   True
total_highest                           130428103
dtype: object

In [119]:
grader.check("q8")

q8 results: All test cases passed!

### Question 9 – Reading Malformed `.csv` Files

`data/malformed.csv` is a file of comma-separated values, containing the following fields:


|column name|description|type|
|---|---|---|
|`'first'`|first name of person|`str`|
|`'last'`|last name of person|`str`|
|`'weight'`|weight of person (lbs)|`float`|
|`'height'`|height of person (in)|`float`|
|`'geo'`|location of person; comma-separated latitude/longitude|`str`|

Unfortunately, the entries contains errors with the placement of commas (`,`) and quotes (`"`) that cause `pandas`' `read_csv` function to fail parsing the file with the default settings. Don't believe us? Try using `pd.read_csv` on `data/malformed.csv` and look at what happens.

As a result, instead of using `pd.read_csv`, you must read in the file manually using Python's built-in `open` function.

Complete the implementation of the function `parse_malformed`, which takes in a file path (`fp`) and returns a parsed, properly-typed DataFrame with the information in the corresponding file. For example, `fp` may be `'data/malformed.csv'`. The DataFrame should contain the columns described in the data description table above (with the specified types).

***Note:*** 
- The only kinds of issues you need your function to handle are comma and quote misplacements; don't try and find any other issues with the CSV. 
- With that said, you should assume that `data/malformed.csv` is a sample of a larger file that has the same sorts of errors, but potentially in different lines. For example, `data/malformed.csv` has an unnecessary quote `"` in line 4, but your function may be called on another CSV that has a perfectly fine line 4 but an unnecessary quote on some other line.
- So, **don't** implement `parse_malformed` assuming that the commas and quotes are mispositioned on specific lines; rather, implement `parse_malformed` such that it can handle these issues on every single line they appear in.
- A good way to proceed is to open `data/malformed.csv` and look carefully at the comma and quote placements.


The first few rows of `parse_malformed('data/malformed.csv')` should be:

<img src="./imgs/example-df.png" width=45%>

In [120]:
def parse_malformed(fp):
    with open(fp, 'r') as fh:
        col_names = fh.readline().split(sep=',')
        col_names = list(map(lambda names : names.strip(), col_names))
        rows = []
        df = pd.DataFrame(columns=col_names)
        for line in fh:
            split_lines = line.split(sep=',')
            a_line = list(map(lambda line : line.replace(",", ""), split_lines))
            a_line = list(map(lambda line : line.replace("\"", ""), a_line))
            a_line = list(map(lambda line : line.strip(), a_line))
            a_line = list(filter(None, a_line))
            a_row = [a_line[0], a_line[1], float(a_line[2]), float(a_line[3]), f"{a_line[4]},{a_line[5]}"]
            rows.append(a_row)
            df = pd.DataFrame(rows, columns=col_names)

    return df

In [121]:
parse_malformed('data\malformed.csv')

       first      last  weight  height          geo
0      Julia    Wagner   142.0    86.0    39.8,15.4
1   Angelica      Rija   155.0    56.0   38.2,-71.7
2      Tyler   Micajah   116.0    73.0     38.0,6.9
3   Kathleen     Nakea   163.0    69.0   36.3,-86.8
4       Axel     Ronit    95.0    74.0   36.8,128.2
..       ...       ...     ...     ...          ...
95   Yasmeen    Jahron   135.0    84.0  38.3,-127.3
96    Meghan  Carlyann   101.0    66.0    36.6,80.5
97      Tess     Shree   146.0    68.0    38.8,64.9
98     Maria    Kalvyn   115.0    51.0   37.1,-90.4
99     Lexie  Cheyenna   151.0    71.0    35.9,86.1

[100 rows x 5 columns]

In [122]:
# Do not edit -- needed for tests
fp = Path('data') / 'malformed.csv'
cols = ['first', 'last', 'weight', 'height', 'geo']
df = parse_malformed(fp)
dg = pd.read_csv(fp, nrows=4, skiprows=10, names=cols)

In [123]:
grader.check("q9")

q9 results: All test cases passed!

## Congratulations! You're done Lab 1! 🏁

As a reminder, all of the work you want to submit needs to be in `lab.py`.

To ensure that all of the work you want to submit is in `lab.py`, we've included a script named `lab-validation.py` in the lab folder. You shouldn't edit it, but instead, you should call it from the command line (e.g. the Terminal) to test your work.

Once you've finished the lab, you should open the command line and run, in the directory for this lab:

```
python lab-validation.py
```

**This will run all of the `grader.check` cells that you see in this notebook, but only using the code in `lab.py` – that is, it doesn't look at any of the code in this notebook. If all of your `grader.check` cells pass in this notebook but not all of them pass in your command line with the above command, then you likely have code in your notebook that isn't in your `lab.py`!**

You can also use `lab-validation.py` to test individual questions. For instance,

```
python lab-validation.py q1 q4 q7 q8
```

will run the `grader.check` cells for Questions 1, 4, 7, and 8 – again, only using the code in `lab.py`. The [video](#Infrastructure-Summary) linked above shows you how to use the script as well.

Once `python lab-validation.py` shows that you're passing all test cases, you're ready to submit your `lab.py` (and only your `lab.py`) to Gradescope. Once submitting to Gradescope, make sure to stick around until all test cases pass.

There is also a call to `grader.check_all()` below in _this_ notebook, but make sure to also follow the steps above.

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [124]:
grader.check_all()

q0 results: All test cases passed!

q1 results: All test cases passed!

q2 results: All test cases passed!

q3 results: All test cases passed!

q4 results: All test cases passed!

q5 results: All test cases passed!

q6 results: All test cases passed!

q6.2 results: All test cases passed!

q7 results: All test cases passed!

q8 results: All test cases passed!

q9 results: All test cases passed!